### ISSUE TITLE
SAP JVM Centos 8 tests failed 

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-java#100]
##### SUMMARY

Ansible verifier tests failed on Centos 8

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

SAP JVM
##### ANSIBLE VERSION

```
2.8.5
```

##### OS / ENVIRONMENT

Centos 8
##### STEPS TO REPRODUCE

```yaml
  inventory:
    group_vars:
      sapjvm:
        java_distribution: sapjvm
        transport: sapjvm-fallback
        java_major_version: 8
```

##### EXPECTED RESULTS

Ansible verivier test should be passed
##### ACTUAL RESULTS

```
    fatal: [test-aws-centos8-sapjvm-8]: FAILED! => changed=true 
      cmd:
      - java
      - -version
      delta: '0:00:00.080198'
      end: '2019-10-23 11:18:33.077975'
      msg: non-zero return code
      rc: 1
      start: '2019-10-23 11:18:32.997777'
      stderr: |-
        ERROR: transport library not found: dt_socket
        ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_LOAD(509)
        JDWP exit error AGENT_ERROR_TRANSPORT_LOAD(196): No transports initialized [debugInit.c:791]
        ERROR: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_LOAD(196)
      stderr_lines: <omitted>
      stdout: ''
      stdout_lines: <omitted>
```
