### ISSUE TITLE
Failed to install security policy for oracle jre

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-java#107]
##### SUMMARY

Failed to install security policy for oracle jre
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

https://github.com/lean-delivery/ansible-role-java/blob/master/tasks/Linux/security_policy.yml
##### ANSIBLE VERSION

```
2.9.1
```

##### OS / ENVIRONMENT

Linux
##### STEPS TO REPRODUCE

```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-java
      java_distribution: oracle_java
      java_package: jdk
      java_major_version: 7
      transport: local
      transport_local: /vagrant/artifatcs/jdk-7u80-linux-x64.tar.gz
      java_unlimited_policy_enabled: true
      java_unlimited_policy_transport: local
      java_unlimited_policy_transport_local: /vagrant/artifatcs/UnlimitedJCEPolicyJDK7.zip
```

##### EXPECTED RESULTS

Role complete succesfully 
##### ACTUAL RESULTS

```
TASK [lean_delivery.java : Apply security policy patch] ****************************************************************************************************************************************included: /home/centos/roles/lean_delivery.java/tasks/Linux/security_policy.yml for localhost

TASK [lean_delivery.java : Fetch oracle security policy with local transport] ******************************************************************************************************************included: /home/centos/roles/lean_delivery.java/tasks/Linux/fetch/security-fetch/security-fetch-local.yml for localhost

TASK [lean_delivery.java : Copy security policy artifact to destination] ***********************************************************************************************************************ok: [localhost]

TASK [lean_delivery.java : Downloaded artifact] ************************************************************************************************************************************************ok: [localhost]

TASK [lean_delivery.java : Unzip patch file] ***************************************************************************************************************************************************changed: [localhost]

TASK [lean_delivery.java : Apply patch file] ***************************************************************************************************************************************************changed: [localhost] => (item=local_policy.jar)
changed: [localhost] => (item=US_export_policy.jar)
ok: [localhost] => (item=README.txt)

TASK [lean_delivery.java : Apply setting] ******************************************************************************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "msg": "Path /usr/java/jre1.7.0_80/jre/lib/security/java.security does not exist !", "rc": 257}
```
