### ISSUE TITLE
Update alternatives failed when installation started from specific file

### ISSUE THREAD

**Issue by DmitriyStoyanov** [lean-delivery/ansible-role-java#12]
##### SUMMARY

Version of java cannot be taken from specified file to install and works as it was 8.181

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.5.5
```

##### STEPS TO REPRODUCE

```yaml
- name: "Install java"
  hosts: all

  roles:
    - role: "ansible-role-java"
      transport: "web"
      transport_web: "https://somehost/somedirectory/jdk-7u191-linux-x64.tar.gz"
```

##### ACTUAL RESULTS

TASK [ansible-role-java : Install java 8.181] ******************************************************************************
ok: [127.0.0.1]

TASK [ansible-role-java : Update alternatives] *****************************************************************************
failed: [127.0.0.1] (item=java) => {"binary": "java", "changed": false, "msg": "Specified path /opt/jdk//jdk1.8.0_181/bin/java does not exist"}
failed: [127.0.0.1] (item=javac) => {"binary": "javac", "changed": false, "msg": "Specified path /opt/jdk//jdk1.8.0_181/bin/javac does not exist"}
failed: [127.0.0.1] (item=jar) => {"binary": "jar", "changed": false, "msg": "Specified path /opt/jdk//jdk1.8.0_181/bin/jar does not exist"}
        to retry, use: --limit @/tmp/ansible/oracle-java.retry

PLAY RECAP *****************************************************************************************************************
127.0.0.1                  : ok=9    changed=0    unreachable=0    failed=1

```

```
