### ISSUE TITLE
macOS Sonoma support

### ISSUE THREAD

**Issue by SPR0STO** [lean-delivery/ansible-role-java#144]
##### SUMMARY

Add Java installation to the macOS Sonoma 

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible [core 2.14.0]
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### OS / ENVIRONMENT

macOS Sonoma

##### STEPS TO REPRODUCE

```yaml
ansible-galaxy role install lean_delivery.java

cat java2Sonoma.yml 
- name: setup Java to macOS Sonoma
  hosts: sonoma_host
  roles:
    - role: lean_delivery.java

ansible-playbook java2Sonoma.yml
```

##### EXPECTED RESULTS

Any version of JDK from availables will be successfully installed in macOS Sonoma hosts

##### ACTUAL RESULTS

```yaml
fatal: [sonoma_host]: FAILED! => {
    "changed": false,
    "msg": "This role does not support 'Darwin' platform.\n  Please contact support@lean-delivery.com\n"
}
```

```

```
