### ISSUE TITLE
JAVA installation on Windows platform

### ISSUE THREAD

**Issue by VitaliStanevich** [lean-delivery/ansible-role-java#16]
##### SUMMARY
JAVA is not installed to Windows hosts with 'win_chocolatey' module because of incorrect Ansible fact is used

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

task/main.yml

task:
- name: "Choose platform based task "

##### ANSIBLE VERSION

```
ansible 2.5.5
```

##### CONFIGURATION

ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = True
ANSIBLE_FORCE_COLOR(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = [u'/etc/ansible/se-provision/playbooks/sdl/vagrant_inventory']
DEFAULT_MODULE_PATH(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = [u'/etc/ansible/se-provision/library']
DEFAULT_ROLES_PATH(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = [u'/etc/ansible/se-provision/roles']
HOST_KEY_CHECKING(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/se-provision/playbooks/sdl/ansible.cfg) = False

##### STEPS TO REPRODUCE

```yaml

- name: Install java
  hosts: windows
  roles:
    - role: ../../roles/ansible-role-java
      java_major_version: 8
      java_package: "jre"
      transport: "win-chocolatey"

```

##### EXPECTED RESULTS

Get jre 8 installed to Windows hosts with win_chocolatey module

##### ACTUAL RESULTS

```
Instead of 'tasks/system/Windows.yml' 'tasks/system/not-supported.yml' is called by 'tasks/main.yml'
```
