### ISSUE TITLE
Maybe you have mistake in README

### ISSUE THREAD

**Issue by zakabluk** [lean-delivery/ansible-role-java#32]
When I have tried to run playbook with example from README 

```
- name: "Install java"
  hosts: all

  roles:
    - role: "lean-delivery.java"
      java_major_version: 8
      java_minor_version: 191
      java_arch: "x64"
      java_package: "jdk"
```

I have got error:

```
[zak@localhost lean_delivery.java]$ ansible-playbook -i host playbook.yml
ERROR! the role 'lean-delivery.java' was not found in /home/zak/.ansible/roles/lean_delivery.java/roles:/home/zak/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/zak/.ansible/roles/lean_delivery.java

The error appears to have been in '/home/zak/.ansible/roles/lean_delivery.java/playbook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: "lean-delivery.java"
      ^ here

```

Because role name in playbook has name **lean-delivery.java** , but folder which was created galaxy have had **lean_delivery.java** (underscore).
