### ISSUE TITLE
Windows package installation failed

### ISSUE THREAD

**Issue by pavelpikta** [lean-delivery/ansible-role-java#59]
##### SUMMARY

Failed to install java package to custom path on Windows
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lean_delivery.java/tasks/Windows/package.yml
##### ANSIBLE VERSION

```
2.7.10
```

##### OS / ENVIRONMENT

Windows Server 2012 R2
##### STEPS TO REPRODUCE

```yaml
---
- name: Install Java
  hosts: windows
  gather_facts: True

  roles:
    - role: "lean_delivery.java"
      java_major_version: 8
      java_package: jdk
      java_tarball_install: False
      java_path: C:\Temp\Java
```

##### ACTUAL RESULTS

TASK [lean_delivery.java : Install java packages] ******************************************************************************************************
changed: [windows.server.com]

TASK [lean_delivery.java : Find java_folder] ******************************************************************************************************
fatal: [windows.server.com]: FAILED! => {
    "changed": false, 
    "examined": 0, 
    "files": [], 
    "matched": 0
}

MSG:

Argument path C:\Temp\Java does not exist cannot get information on

PLAY RECAP ******************************************************************************************************
windows.server.com : ok=23   changed=2    unreachable=0    failed=1   

```

```
