### ISSUE TITLE
Not working with Python3.7

### ISSUE THREAD

**Issue by ToROxI** [lean-delivery/ansible-role-java#92]
##### SUMMARY
Ansible role fails on `Gathering Facts `.

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May  3 2019, 11:24:39) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
- name: install java
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-role-java
      java_package: jdk
      java_major_version: 8
      java_distribution: oracle_java
      transport: s3
      transport_s3_path: jdk-8u212-linux-x64.tar.gz
      transport_s3_bucket: "{{ aws_bucket_name }}"
      transport_s3_aws_access_key: "{{ aws_access_key_id }}"
      transport_s3_aws_secret_key: "{{ aws_secret_access_key }}"
```

##### ACTUAL RESULTS

```
TASK [Gathering Facts] *********************************************************
/usr/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/lib/python3.7/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /root/.ansible/tmp/ansible-tmp-1569748498.059054-219969678795466 `\" && echo ansible-tmp-1569748498.059054-219969678795466=\"` echo /root/.ansible/tmp/ansible-tmp-1569748498.059054-219969678795466 `\" ), exited with result 1", "unreachable": true}
```
